### ISSUE TITLE
Faster LIKE-escaping (code inside)

### ISSUE THREAD

**Issue by aitte2** [shadowhand/latitude#49]
I noticed this "heavy" code that's doing three separate str_replace calls which each has to create a string, parse it and return each string. Which is going to suck if the string is a very long one:

https://github.com/shadowhand/latitude/blob/05b101ea9932705a41e4e23ca0e76c2d87d6eedc/src/LikeValue.php#L8-L20

And you do them in a special order to ensure backslashes are processed first, etc...

I am not 100% sure but I THINK that all of that can be handled like this instead:

```php
$str = 'a\\_b\\c%'; // Input: a\_b\c%
var_dump(strtr($str, ['\\' => '\\\\', '%' => '\\%', '_' => '\\_'])); // Result: a\\\_b\\c\%
```

As PHP's manual says, strtr will not replace a replacement, so that is why I think this should be safe: http://php.net/strtr

And as you can see, it's just a SINGLE function call which handles it all in native C code! No more repeated, wasteful copying back/forth of strings between native `str_replace()` and PHP. :-)

PS: Any other code locations that do this kinda escaping benefits from the same idea... :-) Maybe the library has a generic `escape() / quote()`? I haven't started using it yet, but this idea would be good there too.

**Comment by shadowhand** [comment]
I think this is probably a micro-optimization that would have no real performance benefit. If you can provide benchmarks that prove otherwise, I would be happy to look at it more. The current code is aiming for readability over maximum possible performance. After all, the biggest bottleneck will be the actual database fetch and return. 🤓
